version: "3.9"

services:
  api:
    container_name: "backend"
    build:
      context: ./
      dockerfile: Backend/Dockerfile  
    depends_on:
      - postgres
    volumes:
      - ./Backend:/app/Backend
    env_file:
        - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    ports:
      - 3333:3333
    networks:
      - transcendence
    command: ["npm", "run", "start:dev"]

  frontend:
    container_name: "frontend"
    build:
      context: ./
      dockerfile: Frontend/Dockerfile
    volumes:
      - ./Frontend:/app/Frontend
    ports:
      - 4200:4200
    networks:
      - transcendence
    links:
      - api
    depends_on:
      - api

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    ports:
      - 5432:5432
    networks:
      - transcendence
    
networks:
  transcendence: