version: "3.9"

services:
  api:
    container_name: "backend"
    build:
      context: ./Backend/
      dockerfile: Dockerfile  
    depends_on:
      - postgres
    volumes:
      - ./Backend:/app
      - back_node_modules:/app/node_modules
    env_file:
        - ./Backend/.env
    ports:
      - 3333:3333
    networks:
      - transcendence
    command: ["npm", "run", "start:prod"]

  frontend:
    container_name: "frontend"
    build:
      context: ./Frontend/
      dockerfile: Dockerfile
    volumes:
      - ./Frontend:/app
      - front_node_modules:/app/node_modules
    ports:
      - 4200:4200
    networks:
      - transcendence
    links:
      - api
    command: npx @angular/cli serve

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB : db
      POSTGRES_USER : user
      POSTGRES_PASSWORD : password
    ports:
      - 5432:5432
    networks:
      - transcendence
    


networks:
  transcendence:

volumes:
  back_node_modules:
  front_node_modules: